### ISSUE TITLE
doInit() is required to run before search1(), but test order is not deterministic

### ISSUE THREAD

**Issue by simongray** [clarin-eric/fcs-korp-endpoint#9]
This can result in a `NullPointerException` since, for instance, the `config` field can't be guaranteed to be non-null before being used, i.e. this is the case in: https://github.com/clarin-eric/fcs-korp-endpoint/blob/master/src/test/java/se/gu/spraakbanken/fcs/endpoint/korp/KorpEndpointSearchEngineTest.java#L319

It seems that there is an implicit requirement for `doInit()` to run as a text fixture before `search1()`, since `config` won't be initialised otherwise, yet the `doInit()` method is annotated with `@Test` and the tests are currently _not_ guaranteed to run in the order implied by the source code.

**Comment by Querela** [comment]
You are right. I did update this in the [`pull-8` branch](https://github.com/clarin-eric/fcs-korp-endpoint/compare/pull-8) at 5ea66ddb12a6c20ef08bac0fc76ff3f92c078d42. It should work now.
(_`BeforeClass` will now also initialize the `config` which on error will probably fail the whole test class ..._)

_Based on the original README/build instruction of `mvn war:war` tests were skipped and maybe intended to be private only?_
